# Generated by Django 5.0.1 on 2024-02-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('assessment_year', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('net_income', models.IntegerField()),
                ('net_deduction', models.IntegerField()),
                ('tax', models.IntegerField()),
            ],
            options={
                'db_table': 'history_table',
            },
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
