# Generated by Django 5.0.1 on 2024-02-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='default_QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=1000)),
                ('answers', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'default_QA_table',
            },
        ),
        migrations.CreateModel(
            name='user_QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('Questions', models.CharField(max_length=1000)),
                ('Answers', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'users_QA',
            },
        ),
    ]
